# syntax=docker/dockerfile:experimental
FROM nvidia/cuda:12.8.1-devel-rockylinux9

# Install EPEL and PowerTools repositories
RUN dnf -y upgrade && dnf clean all && \ 
  dnf install -y epel-release dnf-plugins-core 
  # && dnf config-manager --set-enabled powertools

# munge and slurm stuff
ARG MUNGEUSER=16952
ARG MUNGEGROUP=1034
ARG SLURMUSER=16924
ARG SLURMGROUP=1034
RUN groupadd -f -g $SLURMGROUP slurm && \
    useradd -m -c "SLURM workload manager" -d /var/lib/slurm -u $SLURMUSER -g slurm -s /bin/bash slurm

RUN dnf install -y \
    zip unzip \
    python3 \
    python3-devel \
    python3-pip \
    libtiff \
    iputils \
    sudo \
    net-tools \
    openssh-server \
    jq \
    munge

RUN dnf install -y --allowerasing \
    ca-certificates \
    gnupg2 && \
    curl -fsSL https://rpm.nodesource.com/setup_21.x | bash - && \
    dnf install -y nodejs

# RUN curl -fsSL https://www.mongodb.org/static/pgp/server-6.0.asc | gpg --dearmor -o /usr/share/keyrings/mongodb.gpg
RUN echo -e "[mongodb-org-6.0]\nname=MongoDB Repository\nbaseurl=https://repo.mongodb.org/yum/redhat/8/mongodb-org/6.0/x86_64/\ngpgcheck=1\nenabled=1\ngpgkey=file:///usr/share/keyrings/mongodb.gpg" > /etc/yum.repos.d/mongodb-org-6.0.repo && \
    ln -s /usr/lib64/libtiff.so.5 /usr/lib64/libtiff.so.3

RUN groupmod -o -g $MUNGEGROUP munge && \
    usermod -c "MUNGE Uid 'N' Gid Emporium" -d /var/lib/munge -u $MUNGEUSER -g munge -s /sbin/nologin munge && \
    chown -R munge:$MUNGEGROUP /etc/munge

ENV CRYOSPARC_ROOT_DIR=/app
RUN mkdir -p ${CRYOSPARC_ROOT_DIR}
WORKDIR ${CRYOSPARC_ROOT_DIR}

ARG CRYOSPARC_VERSION
ENV CRYOSPARC_VERSION=${CRYOSPARC_VERSION}

ARG CRYOSPARC_LICENSE_ID
ENV CRYOSPARC_LICENSE_ID=${CRYOSPARC_LICENSE_ID}

# install master
ENV CRYOSPARC_MASTER_DIR=${CRYOSPARC_ROOT_DIR}/cryosparc_master

RUN curl -L https://get.cryosparc.com/download/master-latest/5598bde0-13b9-11f0-af32-ef181c1290ef -o cryosparc_master.tar.gz
RUN tar -xzf cryosparc_master.tar.gz

RUN cd ${CRYOSPARC_MASTER_DIR} && \
    sed -i '/^echo "# Other" >> config.sh$/a echo \"CRYOSPARC_FORCE_USER=true\" >> config.sh' ./install.sh && \
    bash ./install.sh --license "$(cat /run/secrets/cryosparc_license_id)" --yes --allowroot && \
    sed -i 's/^export CRYOSPARC_LICENSE_ID=.*$/export CRYOSPARC_LICENSE_ID=TBD/g' ${CRYOSPARC_MASTER_DIR}/config.sh

ARG CRYOSPARC_PATCH
ENV CRYOSPARC_PATCH=${CRYOSPARC_PATCH}

# update patches
RUN if [ ! -z "${CRYOSPARC_PATCH}" ]; then curl -L https://get.cryosparc.com/patch_get/v${CRYOSPARC_VERSION}+${CRYOSPARC_PATCH}/master -o ${CRYOSPARC_ROOT_DIR}/cryosparc_master_patch.tar.gz && \
    tar -xzf ${CRYOSPARC_ROOT_DIR}/cryosparc_master_patch.tar.gz --overwrite --strip-components=1 --directory=${CRYOSPARC_MASTER_DIR} && \
    rm -f ${CRYOSPARC_ROOT_DIR}/cryosparc_master_patch.tar.gz; fi

# patches
RUN sed -i 's:    disk_has_space=.*:    disk_has_space="true":g' ${CRYOSPARC_MASTER_DIR}/bin/cryosparcm

# install worker
ENV CRYOSPARC_WORKER_DIR=${CRYOSPARC_ROOT_DIR}/cryosparc_worker
RUN curl -L https://get.cryosparc.com/download/worker-latest/5598bde0-13b9-11f0-af32-ef181c1290ef -o cryosparc_worker.tar.gz
RUN tar -xzf cryosparc_worker.tar.gz \
    && cd ${CRYOSPARC_WORKER_DIR} \
    && bash ./install.sh --license "$(cat /run/secrets/cryosparc_license_id)" --yes \
    && sed -i '/^echo "# Other" >> config.sh$/a echo \"CRYOSPARC_FORCE_USER=true\" >> config.sh' ./install.sh \
    && sed -i 's/^export CRYOSPARC_LICENSE_ID=.*$/export CRYOSPARC_LICENSE_ID=TBD/g' ${CRYOSPARC_WORKER_DIR}/config.sh

# update patches
RUN if [ ! -z "${CRYOSPARC_PATCH}" ]; then curl -L https://get.cryosparc.com/patch_get/v${CRYOSPARC_VERSION}+${CRYOSPARC_PATCH}/worker -o ${CRYOSPARC_ROOT_DIR}/cryosparc_worker_patch.tar.gz && \
    tar -vxzf ${CRYOSPARC_ROOT_DIR}/cryosparc_worker_patch.tar.gz --overwrite --strip-components=1 --directory=${CRYOSPARC_WORKER_DIR} && \
    rm -f ${CRYOSPARC_ROOT_DIR}/cryosparc_worker_patch.tar.gz; fi

# install cryosparc live
ARG CRYOSPARC_LIVE
RUN --mount=type=secret,id=cryosparc_license_id \
  if [ ! -z $CRYOSPARC_LIVE ]; then cd ${CRYOSPARC_MASTER_DIR} && \
    curl -L "https://get.cryosparc.com/download/master-${CRYOSPARC_LIVE}/$(cat /run/secrets/cryosparc_license_id)" | tar -xz --overwrite --strip-components=1 --directory . && \
    ${CRYOSPARC_MASTER_DIR}/bin/cryosparcm deps && \
    sed -i 's/^export CRYOSPARC_LICENSE_ID=.*$/export CRYOSPARC_LICENSE_ID=TBD/g' ${CRYOSPARC_MASTER_DIR}/config.sh; \
  fi
RUN --mount=type=secret,id=cryosparc_license_id \
  if [ ! -z $CRYOSPARC_LIVE ]; then cd ${CRYOSPARC_WORKER_DIR} && \
    curl -L "https://get.cryosparc.com/download/worker-${CRYOSPARC_LIVE}/$(cat /run/secrets/cryosparc_license_id)" | tar -xz --overwrite --strip-components=1 --directory . && \
    ${CRYOSPARC_WORKER_DIR}/bin/cryosparcw deps && \
    sed -i 's/^export CRYOSPARC_LICENSE_ID=.*$/export CRYOSPARC_LICENSE_ID=TBD/g' ${CRYOSPARC_WORKER_DIR}/config.sh; \
  fi

####
## install motioncor
####
ARG MOTIONCOR2_VERSION=1.6.4
ENV MOTIONCOR2_VERSION=${MOTIONCOR2_VERSION}
RUN cd /usr/local/bin && \
    curl -L 'https://drive.google.com/uc?export=download&id=1hskY_AbXVgrl_BUIjWokDNLZK0c1FLxF' > MotionCor2_${MOTIONCOR2_VERSION}.zip && \
    unzip MotionCor2_${MOTIONCOR2_VERSION}.zip && \
    rm -f MotionCor2_${MOTIONCOR2_VERSION}.zip && \
    ln -sf MotionCor2_${MOTIONCOR2_VERSION}-Cuda100 MotionCor2

COPY entrypoint.bash /entrypoint.bash
COPY cryosparc.sh /cryosparc.sh
COPY cryosparc-server.sh ${CRYOSPARC_MASTER_DIR}/bin/cryosparc-server.sh

ADD slurm /app/slurm

EXPOSE 39000 39001 39002 39003 39004 39006

ENTRYPOINT ["/entrypoint.bash"]
