services:

  cryosparc:
    image: cryosparc-rockylinux9:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cryosparc
    # volumes:
      # - ./cryosparc.sh:/cryosparc.sh
      # - ./entrypoint.bash:/entrypoint.bash
      # - /tmp/mongodb/db:/var/lib/mongo/db
      # - /tmp/cryosparc/u:/u
      # - /tmp/cryosparc/exp:/exp
      # - /tmp/lscratch:/lscratch
    environment:
      - CRYOSPARC_LICENSE_ID=${CRYOSPARC_LICENSE_ID}
      # - JUPYTERHUB_USER=ytl
      # - EXTERNAL_GROUPS=sf:1051,cryo-data:3591,bd:1124
      # - HOMEDIRS=/home
      # - JUPYTERHUB_SERVICE_PREFIX=/user/ytl/
      # - EXTERNAL_UID=1000
      # - EXTERNAL_GROUPS=msnyder:1000
      # - USERNAME=cryosparc
    ports:
      - 39000:39000
      - 39001:39001
      - 39002:39002
      - 39003:39003
      - 39004:39004